CREATE DATABASE [AuditCODB] ON  PRIMARY 
( NAME = N'AuditCODB', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\AuditCODB.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'AuditCODB_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\AuditCODB_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [AuditCODB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AuditCODB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AuditCODB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AuditCODB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AuditCODB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AuditCODB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AuditCODB] SET ARITHABORT OFF 
GO

ALTER DATABASE [AuditCODB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [AuditCODB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AuditCODB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AuditCODB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AuditCODB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AuditCODB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AuditCODB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AuditCODB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AuditCODB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AuditCODB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AuditCODB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [AuditCODB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AuditCODB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AuditCODB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AuditCODB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AuditCODB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AuditCODB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AuditCODB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AuditCODB] SET  READ_WRITE 
GO

ALTER DATABASE [AuditCODB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AuditCODB] SET  MULTI_USER 
GO

ALTER DATABASE [AuditCODB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AuditCODB] SET DB_CHAINING OFF 
GO


