SET QUOTED_IDENTIFIER OFF;
GO
USE [AuditCODB];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

IF OBJECT_ID(N'[dbo].[Coletas]', 'U') IS NOT NULL
    DROP TABLE [dbo].[Coletas];
GO

CREATE TABLE [dbo].[Coletas] (
    [ColetaID] int IDENTITY(1,1) NOT NULL,
    [datacoleta] date  NULL,
	[nmhost] nvarchar(20)  NULL,
	[nmuserlogado] nvarchar(20)  NULL,
	[nmcontdomhost] nvarchar(20)  NULL,
	[uptimehost] nvarchar(50)  NULL,
	[timezonehost] nvarchar(30)  NULL,
	[prochost] nvarchar(50)  NULL,
	[corprochost] nvarchar(50)  NULL,
	[nmsoatualhost] nvarchar(50)  NULL,
	[platsoatualhost] nvarchar(50)  NULL,
	[lingsoatualhost] nvarchar(50)  NULL,
	[qtdmemhost] nvarchar(50)  NULL,
	[qtdmemdisphost] nvarchar(50)  NULL,
	[discosohost] nvarchar(50)  NULL,
	[formatdiscosohost] nvarchar(50)  NULL,
	[tamtotdiscosohost] nvarchar(50)  NULL,
	[tamdispdiscosohost] nvarchar(50)  NULL,
	[nomenicsemfio] nvarchar(50)  NULL,
	[descnicsemfio] nvarchar(50)  NULL,
	[macaddressnicsemfio] nvarchar(50)  NULL,
	[enderipnicsemfio] nvarchar(50)  NULL,
	[nomeniccabo] nvarchar(50)  NULL,
	[descniccabo] nvarchar(50)  NULL,
	[macaddressniccabo] nvarchar(50)  NULL,
	[enderipniccabo] nvarchar(50)  NULL,	
	[placavideo] nvarchar(50)  NULL,
	[resolucaoatual] nvarchar(50)  NULL,
	[impressorainst1] nvarchar(50)  NULL,
	[impressorainst2] nvarchar(50)  NULL,
	[impressorainst3] nvarchar(50)  NULL,
	[impressorainst4] nvarchar(50)  NULL,
	[impressorainst5] nvarchar(50)  NULL,
	[impressorainst6] nvarchar(50)  NULL,
	[impressorainst7] nvarchar(50)  NULL,
	[impressorainst8] nvarchar(50)  NULL,
	[impressorainst9] nvarchar(50)  NULL,
	[chavewindows] nvarchar(50)  NULL,
	[chaveoffice] nvarchar(50)  NULL,
	[instanciasql] nvarchar(50)  NULL,
	[programinstal1] nvarchar(50)  NULL,
	[programinstal2] nvarchar(50)  NULL,
	[programinstal3] nvarchar(50)  NULL,
	[programinstal4] nvarchar(50)  NULL,
	[programinstal5] nvarchar(50)  NULL,
	[programinstal6] nvarchar(50)  NULL,
	[programinstal7] nvarchar(50)  NULL,
	[programinstal8] nvarchar(50)  NULL,
	[programinstal9] nvarchar(50)  NULL,
	[programinstal10] nvarchar(50)  NULL,
	[programinstal11] nvarchar(50)  NULL,
	[programinstal12] nvarchar(50)  NULL,
	[programinstal13] nvarchar(50)  NULL,
	[programinstal14] nvarchar(50)  NULL,
	[programinstal15] nvarchar(50)  NULL,
	[programinstal16] nvarchar(50)  NULL,
	[programinstal17] nvarchar(50)  NULL,
	[programinstal18] nvarchar(50)  NULL,
	[programinstal19] nvarchar(50)  NULL,
	[programinstal20] nvarchar(50)  NULL,
	[programinstal21] nvarchar(50)  NULL,
	[programinstal22] nvarchar(50)  NULL,
	[programinstal23] nvarchar(50)  NULL,
	[programinstal24] nvarchar(50)  NULL,
	[programinstal25] nvarchar(50)  NULL,
	[programinstal26] nvarchar(50)  NULL,
	[programinstal27] nvarchar(50)  NULL,
	[programinstal28] nvarchar(50)  NULL,
	[programinstal29] nvarchar(50)  NULL,
	[programinstal30] nvarchar(50)  NULL,
	[programinstal31] nvarchar(50)  NULL,
	[programinstal32] nvarchar(50)  NULL,
	[programinstal33] nvarchar(50)  NULL,
	[programinstal34] nvarchar(50)  NULL,
	[programinstal35] nvarchar(50)  NULL,
	[programinstal36] nvarchar(50)  NULL,
	[programinstal37] nvarchar(50)  NULL,
	[programinstal38] nvarchar(50)  NULL,
	[programinstal39] nvarchar(50)  NULL,
	[programinstal40] nvarchar(50)  NULL,
	[programinstal41] nvarchar(50)  NULL,
	[programinstal42] nvarchar(50)  NULL,
	[programinstal43] nvarchar(50)  NULL,
	[programinstal44] nvarchar(50)  NULL,
	[programinstal45] nvarchar(50)  NULL,
	[programinstal46] nvarchar(50)  NULL,
	[programinstal47] nvarchar(50)  NULL,
	[programinstal48] nvarchar(50)  NULL,
	[programinstal49] nvarchar(50)  NULL,
	[programinstal50] nvarchar(50)  NULL,
	[programinstal51] nvarchar(50)  NULL,
	[programinstal52] nvarchar(50)  NULL,
	[programinstal53] nvarchar(50)  NULL,
	[programinstal54] nvarchar(50)  NULL,
	[programinstal55] nvarchar(50)  NULL,
	[programinstal56] nvarchar(50)  NULL,
	[programinstal57] nvarchar(50)  NULL,
	[programinstal58] nvarchar(50)  NULL,
	[programinstal59] nvarchar(50)  NULL,
	[programinstal60] nvarchar(50)  NULL,
	[programinstal61] nvarchar(50)  NULL,
	[programinstal62] nvarchar(50)  NULL,
	[programinstal63] nvarchar(50)  NULL,
	[programinstal64] nvarchar(50)  NULL,
	[programinstal65] nvarchar(50)  NULL,
	[programinstal66] nvarchar(50)  NULL,
	[programinstal67] nvarchar(50)  NULL,
	[programinstal68] nvarchar(50)  NULL,
	[programinstal69] nvarchar(50)  NULL,
	[programinstal70] nvarchar(50)  NULL,
	[programinstal71] nvarchar(50)  NULL,
	[programinstal72] nvarchar(50)  NULL,
	[programinstal73] nvarchar(50)  NULL,
	[programinstal74] nvarchar(50)  NULL,
	[programinstal75] nvarchar(50)  NULL,
	[programinstal76] nvarchar(50)  NULL,
	[programinstal77] nvarchar(50)  NULL,
	[programinstal78] nvarchar(50)  NULL,
	[programinstal79] nvarchar(50)  NULL,
	[programinstal80] nvarchar(50)  NULL,
	[programinstal81] nvarchar(50)  NULL,
	[programinstal82] nvarchar(50)  NULL,
	[programinstal83] nvarchar(50)  NULL,
	[programinstal84] nvarchar(50)  NULL,
	[programinstal85] nvarchar(50)  NULL,
	[programinstal86] nvarchar(50)  NULL,
	[programinstal87] nvarchar(50)  NULL,
	[programinstal88] nvarchar(50)  NULL,
	[programinstal89] nvarchar(50)  NULL,
	[programinstal90] nvarchar(50)  NULL,
	[programinstal91] nvarchar(50)  NULL,
	[programinstal92] nvarchar(50)  NULL,
	[programinstal93] nvarchar(50)  NULL,
	[programinstal94] nvarchar(50)  NULL,
	[programinstal95] nvarchar(50)  NULL,
	[programinstal96] nvarchar(50)  NULL,
	[programinstal97] nvarchar(50)  NULL,
	[programinstal98] nvarchar(50)  NULL,
	[programinstal99] nvarchar(50)  NULL,
	[programinstal100] nvarchar(50)  NULL,
	
);
GO
ALTER TABLE [dbo].[Coletas]
ADD CONSTRAINT [PK_Coletas]
    PRIMARY KEY CLUSTERED ([ColetaID] ASC);

	select * from Coletas